import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { Recipe, PlanType } from '../backend';
import { useSaveRecipe } from '../hooks/useQueries';
import { Clock, ChefHat, Bookmark, Share2, Download, CheckCircle, Loader2, Leaf, Zap } from 'lucide-react';
import { toast } from 'sonner';
import UpgradePromptModal from './UpgradePromptModal';

interface ParsedRecipe {
    name: string;
    cookingTime: string;
    difficulty: string;
    ingredients: string[];
    instructions: string[];
    nutrition?: {
        calories: string;
        protein: string;
        carbs: string;
        fat: string;
    };
}

function parseRecipe(raw: string): ParsedRecipe {
    try {
        const parsed = JSON.parse(raw);
        if (parsed.name || parsed.recipeName) {
            return {
                name: parsed.name || parsed.recipeName || 'Delicious Recipe',
                cookingTime: parsed.cookingTime || parsed.cooking_time || '20 minutes',
                difficulty: parsed.difficulty || 'Easy',
                ingredients: Array.isArray(parsed.ingredients) ? parsed.ingredients : [],
                instructions: Array.isArray(parsed.instructions) ? parsed.instructions :
                    Array.isArray(parsed.steps) ? parsed.steps : [],
                nutrition: parsed.nutrition,
            };
        }
    } catch {
        // Not JSON, parse as text
    }

    // Parse text format
    const lines = raw.split('\n').filter(l => l.trim());
    const name = lines[0]?.replace(/^#+\s*/, '').replace(/\*\*/g, '').trim() || 'Delicious Recipe';

    const cookingTimeMatch = raw.match(/cooking time[:\s]+([^\n]+)/i);
    const difficultyMatch = raw.match(/difficulty[:\s]+([^\n]+)/i);

    const ingredientsStart = raw.toLowerCase().indexOf('ingredient');
    const instructionsStart = raw.toLowerCase().indexOf('instruction') !== -1
        ? raw.toLowerCase().indexOf('instruction')
        : raw.toLowerCase().indexOf('step');

    let ingredients: string[] = [];
    let instructions: string[] = [];

    if (ingredientsStart !== -1 && instructionsStart !== -1) {
        const ingredientSection = raw.slice(ingredientsStart, instructionsStart);
        ingredients = ingredientSection.split('\n')
            .filter(l => l.trim().match(/^[-•*\d]/))
            .map(l => l.replace(/^[-•*\d.)\s]+/, '').trim())
            .filter(Boolean);

        const instructionSection = raw.slice(instructionsStart);
        instructions = instructionSection.split('\n')
            .filter(l => l.trim().match(/^[-•*\d]/))
            .map(l => l.replace(/^[-•*\d.)\s]+/, '').trim())
            .filter(Boolean);
    }

    return {
        name,
        cookingTime: cookingTimeMatch?.[1]?.trim() || '20 minutes',
        difficulty: difficultyMatch?.[1]?.trim() || 'Easy',
        ingredients: ingredients.length > 0 ? ingredients : ['See recipe details below'],
        instructions: instructions.length > 0 ? instructions : lines.slice(1).filter(l => l.trim()),
    };
}

interface RecipeCardProps {
    recipe: Recipe;
    planType?: PlanType;
    showNutrition?: boolean;
    onRemove?: () => void;
}

export default function RecipeCard({ recipe, planType, showNutrition, onRemove }: RecipeCardProps) {
    const [saved, setSaved] = useState(false);
    const [showUpgrade, setShowUpgrade] = useState(false);
    const saveRecipe = useSaveRecipe();

    const isPro = planType === PlanType.pro || planType === PlanType.premium;
    const isPremium = planType === PlanType.premium;
    const parsed = parseRecipe(recipe.generatedRecipe);

    const difficultyColor = parsed.difficulty.toLowerCase().includes('easy')
        ? 'bg-accent text-accent-foreground'
        : parsed.difficulty.toLowerCase().includes('medium')
            ? 'bg-yellow-100 text-yellow-800'
            : 'bg-red-100 text-red-800';

    const handleSave = async () => {
        if (!isPro) {
            setShowUpgrade(true);
            return;
        }
        try {
            await saveRecipe.mutateAsync(recipe.id);
            setSaved(true);
            toast.success('Recipe saved! 🌿');
        } catch (err: any) {
            toast.error(err?.message || 'Failed to save recipe');
        }
    };

    const handleShare = async () => {
        const text = `🍳 ${parsed.name}\n\n⏱ ${parsed.cookingTime} | ${parsed.difficulty}\n\nIngredients:\n${parsed.ingredients.map(i => `• ${i}`).join('\n')}\n\nInstructions:\n${parsed.instructions.map((s, i) => `${i + 1}. ${s}`).join('\n')}\n\nGenerated by GreenChef AI 🌿`;
        try {
            await navigator.clipboard.writeText(text);
            toast.success('Recipe copied to clipboard!');
        } catch {
            toast.error('Could not copy to clipboard');
        }
    };

    const handleDownload = () => {
        if (!isPro) {
            setShowUpgrade(true);
            return;
        }
        const content = `${parsed.name}\n${'='.repeat(parsed.name.length)}\n\nCooking Time: ${parsed.cookingTime}\nDifficulty: ${parsed.difficulty}\n\nIngredients:\n${parsed.ingredients.map(i => `• ${i}`).join('\n')}\n\nInstructions:\n${parsed.instructions.map((s, i) => `${i + 1}. ${s}`).join('\n')}`;
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${parsed.name.replace(/\s+/g, '-').toLowerCase()}.txt`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success('Recipe downloaded!');
    };

    return (
        <>
            <Card className="rounded-2xl shadow-card border border-border overflow-hidden animate-fade-in">
                {/* Header */}
                <CardHeader className="bg-gradient-to-r from-primary/10 to-accent pb-4">
                    <div className="flex items-start justify-between gap-3">
                        <div className="flex-1">
                            <div className="flex items-center gap-2 mb-1">
                                <ChefHat className="w-4 h-4 text-primary" />
                                <span className="text-xs font-medium text-primary uppercase tracking-wide">AI Generated</span>
                            </div>
                            <CardTitle className="text-xl font-bold text-foreground leading-tight">
                                {parsed.name}
                            </CardTitle>
                        </div>
                        <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${difficultyColor} shrink-0`}>
                            {parsed.difficulty}
                        </span>
                    </div>
                    <div className="flex items-center gap-4 mt-2">
                        <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
                            <Clock className="w-4 h-4 text-primary" />
                            <span>{parsed.cookingTime}</span>
                        </div>
                        <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
                            <Leaf className="w-4 h-4 text-primary" />
                            <span>{recipe.ingredientsInput.length} ingredients</span>
                        </div>
                    </div>
                </CardHeader>

                <CardContent className="p-5 space-y-5">
                    {/* Ingredients */}
                    <div>
                        <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground mb-2.5">
                            Ingredients Used
                        </h3>
                        <div className="flex flex-wrap gap-2">
                            {parsed.ingredients.map((ing, i) => (
                                <span key={i} className="ingredient-chip">
                                    {ing}
                                </span>
                            ))}
                        </div>
                    </div>

                    <Separator />

                    {/* Instructions */}
                    <div>
                        <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground mb-3">
                            Step-by-Step Instructions
                        </h3>
                        <ol className="space-y-3">
                            {parsed.instructions.map((step, i) => (
                                <li key={i} className="flex gap-3">
                                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary text-primary-foreground text-xs font-bold flex items-center justify-center mt-0.5">
                                        {i + 1}
                                    </span>
                                    <p className="text-sm text-foreground leading-relaxed">{step}</p>
                                </li>
                            ))}
                        </ol>
                    </div>

                    {/* Nutrition (Premium only) */}
                    {showNutrition && isPremium && (
                        <>
                            <Separator />
                            <div>
                                <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground mb-3 flex items-center gap-1.5">
                                    <Zap className="w-4 h-4 text-primary" />
                                    Nutrition Breakdown
                                </h3>
                                <div className="grid grid-cols-4 gap-2">
                                    {[
                                        { label: 'Calories', value: parsed.nutrition?.calories || '~320 kcal' },
                                        { label: 'Protein', value: parsed.nutrition?.protein || '~12g' },
                                        { label: 'Carbs', value: parsed.nutrition?.carbs || '~45g' },
                                        { label: 'Fat', value: parsed.nutrition?.fat || '~8g' },
                                    ].map(n => (
                                        <div key={n.label} className="bg-accent rounded-xl p-2.5 text-center">
                                            <div className="text-sm font-bold text-foreground">{n.value}</div>
                                            <div className="text-xs text-muted-foreground">{n.label}</div>
                                        </div>
                                    ))}
                                </div>
                                <p className="text-xs text-muted-foreground mt-2">* Estimated values</p>
                            </div>
                        </>
                    )}

                    {/* Actions */}
                    <Separator />
                    <div className="flex flex-wrap gap-2">
                        <Button
                            variant="default"
                            size="sm"
                            className="rounded-xl flex-1 sm:flex-none"
                            onClick={handleSave}
                            disabled={saveRecipe.isPending || saved}
                        >
                            {saveRecipe.isPending ? (
                                <Loader2 className="w-4 h-4 mr-1.5 animate-spin" />
                            ) : saved ? (
                                <CheckCircle className="w-4 h-4 mr-1.5" />
                            ) : (
                                <Bookmark className="w-4 h-4 mr-1.5" />
                            )}
                            {saved ? 'Saved' : 'Save'}
                            {!isPro && <span className="ml-1 text-xs opacity-70">Pro</span>}
                        </Button>
                        <Button
                            variant="outline"
                            size="sm"
                            className="rounded-xl flex-1 sm:flex-none"
                            onClick={handleShare}
                        >
                            <Share2 className="w-4 h-4 mr-1.5" />
                            Share
                        </Button>
                        <Button
                            variant="outline"
                            size="sm"
                            className="rounded-xl flex-1 sm:flex-none"
                            onClick={handleDownload}
                        >
                            <Download className="w-4 h-4 mr-1.5" />
                            Download
                            {!isPro && <span className="ml-1 text-xs opacity-70">Pro</span>}
                        </Button>
                        {onRemove && (
                            <Button
                                variant="outline"
                                size="sm"
                                className="rounded-xl text-destructive hover:text-destructive"
                                onClick={onRemove}
                            >
                                Remove
                            </Button>
                        )}
                    </div>
                </CardContent>
            </Card>

            <UpgradePromptModal open={showUpgrade} onClose={() => setShowUpgrade(false)} />
        </>
    );
}
