/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MealPlanner {
  'id' : string,
  'weekPlan' : string,
  'userId' : Principal,
  'createdAt' : Time,
}
export type PlanType = { 'pro' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface Recipe {
  'id' : string,
  'ingredientsInput' : Array<string>,
  'userId' : Principal,
  'createdAt' : Time,
  'generatedRecipe' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface User {
  'principal' : Principal,
  'dailyRecipeCount' : bigint,
  'createdAt' : Time,
  'email' : string,
  'dailyLimit' : bigint,
  'planType' : PlanType,
}
export interface UserProfile {
  'dailyRecipeCount' : bigint,
  'createdAt' : Time,
  'email' : string,
  'dailyLimit' : bigint,
  'planType' : PlanType,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetAllUsers' : ActorMethod<[], Array<User>>,
  'adminGetStats' : ActorMethod<
    [],
    { 'totalUsers' : bigint, 'totalRecipes' : bigint }
  >,
  'adminSetUserPlan' : ActorMethod<[Principal, PlanType], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createUser' : ActorMethod<[string], User>,
  'deleteSavedRecipe' : ActorMethod<[string], undefined>,
  'generateMealPlan' : ActorMethod<[string], MealPlanner>,
  'generateRecipe' : ActorMethod<[Array<string>], Recipe>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSavedRecipes' : ActorMethod<[Principal], Array<Recipe>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserMealPlans' : ActorMethod<[Principal], Array<MealPlanner>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRecipes' : ActorMethod<[Principal], Array<Recipe>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRecipe' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'upgradePlan' : ActorMethod<[PlanType], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];