/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PlanType = IDL.Variant({
  'pro' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'dailyRecipeCount' : IDL.Nat,
  'createdAt' : Time,
  'email' : IDL.Text,
  'dailyLimit' : IDL.Nat,
  'planType' : PlanType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const MealPlanner = IDL.Record({
  'id' : IDL.Text,
  'weekPlan' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
});
export const Recipe = IDL.Record({
  'id' : IDL.Text,
  'ingredientsInput' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'generatedRecipe' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'dailyRecipeCount' : IDL.Nat,
  'createdAt' : Time,
  'email' : IDL.Text,
  'dailyLimit' : IDL.Nat,
  'planType' : PlanType,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'adminGetStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalUsers' : IDL.Nat, 'totalRecipes' : IDL.Nat })],
      ['query'],
    ),
  'adminSetUserPlan' : IDL.Func([IDL.Principal, PlanType], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text], [User], []),
  'deleteSavedRecipe' : IDL.Func([IDL.Text], [], []),
  'generateMealPlan' : IDL.Func([IDL.Text], [MealPlanner], []),
  'generateRecipe' : IDL.Func([IDL.Vec(IDL.Text)], [Recipe], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSavedRecipes' : IDL.Func([IDL.Principal], [IDL.Vec(Recipe)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserMealPlans' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MealPlanner)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRecipes' : IDL.Func([IDL.Principal], [IDL.Vec(Recipe)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRecipe' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'upgradePlan' : IDL.Func([PlanType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PlanType = IDL.Variant({
    'pro' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'dailyRecipeCount' : IDL.Nat,
    'createdAt' : Time,
    'email' : IDL.Text,
    'dailyLimit' : IDL.Nat,
    'planType' : PlanType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const MealPlanner = IDL.Record({
    'id' : IDL.Text,
    'weekPlan' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Text,
    'ingredientsInput' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'generatedRecipe' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'dailyRecipeCount' : IDL.Nat,
    'createdAt' : Time,
    'email' : IDL.Text,
    'dailyLimit' : IDL.Nat,
    'planType' : PlanType,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'adminGetStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalUsers' : IDL.Nat, 'totalRecipes' : IDL.Nat })],
        ['query'],
      ),
    'adminSetUserPlan' : IDL.Func([IDL.Principal, PlanType], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text], [User], []),
    'deleteSavedRecipe' : IDL.Func([IDL.Text], [], []),
    'generateMealPlan' : IDL.Func([IDL.Text], [MealPlanner], []),
    'generateRecipe' : IDL.Func([IDL.Vec(IDL.Text)], [Recipe], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSavedRecipes' : IDL.Func([IDL.Principal], [IDL.Vec(Recipe)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserMealPlans' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MealPlanner)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRecipes' : IDL.Func([IDL.Principal], [IDL.Vec(Recipe)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRecipe' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'upgradePlan' : IDL.Func([PlanType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };